import type { Metadata } from "next";
import { unstable_ViewTransition as ViewTransition } from 'react'
import { Geist, Geist_Mono  } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";


// components
import Header from "@components/Header/Header";
import { FilterBarProvider } from "@/app/contexts/FilterBarContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <style>
@import url('https://fonts.googleapis.com/css2?family=Chiron+GoRound+TC:wght@200..900&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300..900;1,9..144,300..900&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&family=Sora:wght@400;500;600&display=swap');
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Instrument+Sans:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');
</style>
      </head>
      <body>
        <FilterBarProvider>
        <Header />

        <ViewTransition>{children}</ViewTransition>
        </FilterBarProvider>

        <footer>
          <div className="container">
            <div className="row">
              <div className="col">
                <div className="text-center">
                  <p>© Intelligent Project 2002-{new Date().getFullYear()}. All rights reserved</p>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
