import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";


// components
import Header from "@components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />

        {children}

        <footer>
          <div className="container">
            <div className="row">
              <div className="col">
                <div className="text-center">
                  <p>© Intelligent Project 2002-{new Date().getFullYear()}. All rights reserved</p>
                </div>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
